name: "Hello workflow"

on:
  push:
    branches:
      - master
      - prod


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello"
        run: echo "hello"